### ISSUE TITLE
Plugin 1 specified in "base" provided an invalid property of "_parallelBabel"

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-htmlbars-inline-precompile#90]
Occurring in 1.0.

```
Error: Plugin 1 specified in "base" provided an invalid property of "_parallelBabel"
    at Plugin.init
```

 Seen here:

https://github.com/kellyselden/package-hint-historic-resolver/pull/435
https://travis-ci.org/kellyselden/package-hint-historic-resolver/jobs/259946508#L2824

https://github.com/ember-fastboot/ember-cli-fastboot/pull/463
https://ci.appveyor.com/project/embercli/ember-cli-fastboot/build/197/job/rsjru7fvih38l8qb#L187

**Comment by rwjblue** [comment]
@mikrostew - Can you take a look?

**Comment by mikrostew** [comment]
Looks like https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/pull/91 fixes the main error here.

But I am still seeing this warning twice when running the tests for kellyselden/package-hint-historic-resolver:
```
broccoli-babel-transpiler is opting out of caching due to a plugin that does not provide a caching strategy: `() => __dirname`.
```

I think ember-cli needs to use broccoli-babel-transpiler 6.1.2, which fixes this issue as well.

**Comment by mikrostew** [comment]
The caching error is fixed by https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/pull/93.

@kellyselden - I reran the tests for `package-hint-historic-resolver` and that is working for me locally. I had to bump ember-cli-babel to "^6.7.1" for `ember-cli-fastboot` and that is working for me now as well. Does this fix the issue?

**Comment by kellyselden** [comment]
This is still happening in v1.0.1.

https://travis-ci.org/kellyselden/package-hint-historic-resolver/jobs/261442779#L2804

**Comment by mikrostew** [comment]
Ah I was reproducing this the wrong way - running `npm run test` was working for me, but on travis this is running code coverage, like `COVERAGE=true npm run test:base`, which fails.

These changes are not playing nicely with `ember-cli-code-coverage`. This is designed to work in the build pipeline, where the plugins are run through broccoli-babel-transpiler which converts any of this parallel stuff into the form that babel expects. But ember-cli-code-coverage is using babel outside of this, and seeing the plugin objects before they are converted.

**Comment by kellyselden** [comment]
Ok it appears this is now just an issue with how it works with ember-cli-code-coverage.

@mikrostew So you know which project has to change to work, this or them? If them, I can close this and open an issue over there.

**Comment by rwjblue** [comment]
We need to update ember-cli-code-coverage so that it doesn't have its own babel transpilation step.

**Comment by kellyselden** [comment]
Cross linked https://github.com/kategengler/ember-cli-code-coverage/issues/133
